### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by pschulz** [yongkangchen/log-console#13] opened 2015-06-09 14:35 UTC
[Enter steps to reproduce below:]

1. Started atom.

**Atom Version**: 0.207.0
**System**: Mac OS X 10.9.5
**Thrown From**: [log-console](https://github.com/yongkangchen/log-console) package, v0.2.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/patrick/.atom/packages/log-console/lib/log-console.coffee:19

TypeError: undefined is not a function
  at Object.module.exports.LogConsole.activate (/Users/patrick/.atom/packages/log-console/lib/log-console.coffee:19:42)
  at doActive (/Users/patrick/.atom/packages/log-console/lib/main.coffee:8:9)
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Project.module.exports.Project.addPath (/Applications/Atom.app/Contents/Resources/app.asar/src/project.js:274:29)
  at EventEmitter.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:37:32)
  at emitTwo (events.js:87:13)
  at EventEmitter.emit (events.js:169:7)

```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
ascii-codes, v0.3.3
compare-files, v0.4.1
emmet, v2.3.10
hex, v0.6.2
html-entities, v0.4.0
language-puppet, v0.12.0
linter, v0.12.6
linter-php, v0.0.15
linter-xmllint, v0.0.6
log-console, v0.2.0
node-debugger, v1.0.5
project-manager, v1.15.10

# Dev
No dev packages
```

**Comment by kankaristo** [comment] 2015-06-12 18:48
I think this is a duplicate of https://github.com/yongkangchen/log-console/issues/12?

**Closed** 2015-08-21 05:27 UTC
